# name: pong

secrets:
  hash_key:
    file: ./secrets/hash_key.txt
  api_key:
    file: ./secrets/api_key.txt
  auth_key:
    file: ./secrets/auth_key.txt
  cookie_key:
    file: ./secrets/cookie_key.txt

services:

  api-gateway:
    container_name: api-gateway
    build: 
      context: ./api-gateway
      args:
        API_PORT: ${API_PORT}
    env_file:
      - ".env"
    depends_on:
      nginx:
        condition: service_started
    volumes:
      - ssl_certs:/etc/ssl # For nginx SSL certs
      - ./api-gateway:/app
      - ./config:/app/config # Dev only ? 
    networks:
      - pongnet
    restart: always

  user-service:
    container_name: user-service
    build: ./user-service
    env_file:
      - ".env"
    volumes:
      - ssl_certs:/etc/ssl # For nginx SSL certs
      - ./user-service:/app # Dev only,prod = pas de volume, seulement copie des fichiers.
      - ./config:/app/config
    networks:
      - pongnet
    secrets:
      - hash_key
      - api_key
      - auth_key
      - cookie_key
    restart: always

  game-service:
    container_name: game-service
    build: 
      context: ./game-service
      args:
        WS_PORT: ${GAME_WS_PORT}
    env_file:
      - ".env"
    volumes:
      - ssl_certs:/etc/ssl # For nginx SSL certs
      - ./game-service:/app # Dev only,prod = pas de volume, seulement copie des fichiers.
      - ./config:/app/config # Dev only
    networks:
      - pongnet
    secrets:
      - hash_key
      - api_key
      - cookie_key
    restart: always

  session-service:
    container_name: session-service
    build: 
      context: ./session-service
      args: 
        WS_PORT: ${SESSION_WS_PORT}
    env_file:
      - ".env"
    volumes:
      - ssl_certs:/etc/ssl # For nginx SSL certs
      - ./session-service:/app # Dev only,prod = pas de volume, seulement copie des fichiers.
      - ./config:/app/config # Dev only,prod = pas de volume, seulement copie des fichiers.
    networks:
      - pongnet
    secrets:
      - hash_key
      - api_key
      - cookie_key
    restart: always

  nginx:
    container_name: nginx
    build: ./nginx
    env_file:
      - ".env"
    ports:
      - "8080:80"
      - "4443:443"
    volumes:
      - ssl_certs:/etc/ssl # For nginx SSL certs
      - frontend_dist:/usr/share/nginx/html # necessary in prod
      - avatar_uploads:/app/uploads #share with upload service
    networks:
      - pongnet
    restart: always

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file: ".env"
    ports:
      - "5173:5173" # Dev only
    volumes:
      - ./frontend:/app # Dev only, prod = pas de volume, seulement copie des fichiers.
      - frontend_dist:/app/dist # Prod volume for nginx
      - ./config:/app/config # Dev only
    networks:
      - pongnet

  upload-service:
    build: ./upload-service
    env_file:
      - ".env"
    container_name: upload-service
    volumes:
      - ssl_certs:/etc/ssl # For nginx SSL certs
      - ./upload-service:/app # Dev only,prod = pas de volume, seulement copie des fichiers.
      - avatar_uploads:/app/uploads # share with nginx
      - ./config:/app/config # Dev only,prod = pas de volume, seulement copie des fichiers.
    secrets:
      - hash_key
      - api_key
      - cookie_key
    networks:
      - pongnet
    restart: always

volumes:
  frontend_dist:
  avatar_uploads:
  ssl_certs:

networks:
  pongnet:
    driver: bridge

